"""Added courses and xp in User

Revision ID: 9ddaeaf211c9
Revises: d652f91df6d2
Create Date: 2025-09-19 20:22:52.541332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9ddaeaf211c9'
down_revision: Union[str, Sequence[str], None] = 'd652f91df6d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('direction', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='courselevel'), nullable=False),
    sa.Column('duration_hours', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # Добавляем колонку xp как nullable
    op.add_column('users', sa.Column('xp', sa.Integer(), nullable=True))
    # Обновляем все существующие записи, устанавливая значение по умолчанию
    op.execute("UPDATE users SET xp = 0 WHERE xp IS NULL")
    # Теперь делаем колонку NOT NULL
    op.alter_column('users', 'xp', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'xp')
    op.drop_table('courses')
    # ### end Alembic commands ###
