"""Added jobs model

Revision ID: abe8084bfe0f
Revises: 9ddaeaf211c9
Create Date: 2025-09-19 23:50:37.898559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'abe8084bfe0f'
down_revision: Union[str, Sequence[str], None] = '9ddaeaf211c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('department', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('level', sa.Enum('INTERN', 'JUNIOR', 'MIDDLE', 'SENIOR', 'LEAD', 'MANAGER', name='joblevel'), nullable=False),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'CONTRACT', 'INTERNSHIP', name='employmenttype'), nullable=False),
    sa.Column('location', sqlmodel.AutoString(length=255), nullable=True),
    sa.Column('remote_available', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.AutoString(), nullable=False),
    sa.Column('requirements', sqlmodel.AutoString(), nullable=False),
    sa.Column('responsibilities', sqlmodel.AutoString(), nullable=False),
    sa.Column('required_skills', sqlmodel.AutoString(), nullable=True),
    sa.Column('min_experience_years', sa.Integer(), nullable=True),
    sa.Column('max_experience_years', sa.Integer(), nullable=True),
    sa.Column('average_salary', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sqlmodel.AutoString(length=10), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'CLOSED', 'DRAFT', name='jobstatus'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
