"""Add new CV fields

Revision ID: d652f91df6d2
Revises: 2413bdff9a4a
Create Date: 2025-09-19 20:06:17.475333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd652f91df6d2'
down_revision: Union[str, Sequence[str], None] = '2413bdff9a4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cvs', sa.Column('additional_education', sqlmodel.AutoString(), nullable=True))
    op.add_column('cvs', sa.Column('current_role', sqlmodel.AutoString(), nullable=True))
    op.add_column('cvs', sa.Column('responsibilities', sqlmodel.AutoString(), nullable=True))
    op.add_column('cvs', sa.Column('department', sqlmodel.AutoString(), nullable=True))
    op.add_column('cvs', sa.Column('grade', sqlmodel.AutoString(), nullable=True))
    op.add_column('cvs', sa.Column('specialization', sqlmodel.AutoString(), nullable=True))
    op.add_column('cvs', sa.Column('competencies', sqlmodel.AutoString(), nullable=True))
    op.add_column('cvs', sa.Column('comments', sqlmodel.AutoString(), nullable=True))
    op.add_column('cvs', sa.Column('career_path', sqlmodel.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cvs', 'career_path')
    op.drop_column('cvs', 'comments')
    op.drop_column('cvs', 'competencies')
    op.drop_column('cvs', 'specialization')
    op.drop_column('cvs', 'grade')
    op.drop_column('cvs', 'department')
    op.drop_column('cvs', 'responsibilities')
    op.drop_column('cvs', 'current_role')
    op.drop_column('cvs', 'additional_education')
    # ### end Alembic commands ###
