name: markdown-lint
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  markdown-lint:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: DavidAnson/markdownlint-cli2-action@v20.0.0
